server:
  applicationConnectors:
    - type: http
      port: 3000
database:
  driverClass: org.postgresql.Driver
  user: coursewizmanager
  password: coursewiz123
  url: jdbc:postgresql://localhost:5432/coursewiz
  maxSize: 10
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: update