server:
  applicationConnectors:
    - type: http
      port: 3000
database:
  driverClass: org.postgresql.Driver
  user: coursewizmanager
  password: coursewiz123
  url: jdbc:postgresql://localhost:5432/coursera
  maxSize: 10
logging:
  level: INFO
  appenders:
    - type: console